version: "3.8"

services:
  backend:
    build: .
    container_name: job-board-backend
    ports:
      - "3000:3000"
    environment:
      - DB_HOST=db
      - DB_USER=root
      - DB_PASSWORD=yourpassword
      - DB_NAME=job_board
      - PORT=3000
    volumes:
      - .:/app
    depends_on:
      - db
    command: npm run dev

  db:
    image: mysql:8
    container_name: job-board-db
    environment:
      MYSQL_ROOT_PASSWORD: yourpassword
      MYSQL_DATABASE: job_board
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"

volumes:
  mysql_data:
